# Generated by Django 4.2.1 on 2023-05-31 08:31

from django.db import migrations

def kategoriafeltolt(apps,schema_editor):
    Kategoria = apps.get_model("app", "Kategoria")
    kategoria_lista = ['Termeszetvedelem', 'java progarmozas', 'Weblapfejlesztes']
    for i in range(len(kategoria_lista)):
        k =  Kategoria(i + 1,kategoria_lista[i])
        k.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(kategoriafeltolt)
    ]
